### ISSUE TITLE
Improve pagination support

### ISSUE THREAD

**Issue by rsullivan00** [Rsullivan00/apollo-link-json-api#18]
Pagination can be currently supported in a limited fashion by manually paging outside of `apollo-link-json-api` with component state:

```js
import React from 'react';
import gql from 'graphql-tag';
import { Query } from 'react-apollo';

const AUTHORS_QUERY = gql`
  query AuthorsQuery($page: Integer!) {
    authors(page: $page) @jsonapi(path: "/authors?page={args.page}") {
      id
    }
  }
`;

const AuthorsList = () => {
  const [page, setPage] = useState(1);

  return (
    <Query query={AUTHORS_QUERY} variables={{ page: 1 }}>
      {({ loading, data, fetchMore }) => {
        if (loading) {
          return 'loading';
        }
        return (
          <>
            <div>
              {data.authors.map(({ id }) => (
                <div>Author {id} loaded</div>
              ))}
            </div>
            <button
              onClick={() => {
                setPage(page + 1);
                fetchMore({
                  variables: { page: page + 1 },

                  updateQuery: (prev, { fetchMoreResult }) => {
                    if (!fetchMoreResult) return prev;
                    return {
                      authors: [...prev.authors, ...fetchMoreResult.authors],
                    };
                  },
                });
              }}
            >
              Moar
            </button>
          </>
        );
      }}
    </Query>
  );
};

export default AuthorsList;
```

This sort of works, but with this pagination setup, we should be able to know when we are done loading resources, yet that isn't available through `apollo-link-json-api`.

In the JSON APIs I currently work with, that pagination information is returned in the top-level `meta` and `links` fields in a list request. For example, a request for `GET /authors?page=1` would return

```js
{
  data: [...],
  meta: { record_count: 123 },
  links: {
    first: 'https://example.com/authors?page=1',
    next: 'https://example.com/authors?page=2',
    last: 'https://example.com/authors?page=5'
  }
}
```

And the `links.next` key will no longer be available if we are on the last page.

**Comment by rsullivan00** [comment]
Proposal 1: Preserve `meta` and `links` fields and nest listed resources under a `resources` key.

```es6
const AUTHORS_QUERY = gql`
  query AuthorsQuery($page: Integer!) {
    authors(page: $page) @jsonapi(path: "/authors?page={args.page}") {
      resources {
        id
      }
      meta {
        recordCount
      }
      links {
        next
      }
    }
  }
`;
```

Pros:
- Provides access to top-level items in the JSON API spec you can't currently access

Cons:
- Adds a layer of nesting to resource lists
- This wouldn't be necessary for APIs with cursor-based pagination, since they can paginate using the last loaded resource.
- `resource` key is "magic"--you just have to know that it's there.

**Comment by rsullivan00** [comment]
Proposal 2: Preserve `meta`, `links`, and `data` fields.

```es6
const AUTHORS_QUERY = gql`
  query AuthorsQuery($page: Integer!) {
    authors(page: $page) @jsonapi(path: "/authors?page={args.page}") {
      data {
        id
      }
      meta {
        recordCount
      }
      links {
        next
      }
    }
  }
`;
```

```es6
const AUTHOR_QUERY = gql`
  query AuthorQuery($id: Integer!) {
    author(id: $id) @jsonapi(path: "/authors/{args.id}?include=book") {
      data {
        id
        books {
          links {
            related
          }
          data {
            links {
              self
            }
            title
          }
        }
      }
      meta {
        something
      }
    }
  }
`;
```

Pros:
- Supports `meta`/`links` for both lists and single resources
- Works on nested related resources
- Disambiguates relationship links from links on the actual related resource

Cons:
- `data` key is sort of ambiguous (but at least it's not really "magic")
- Adds more nesting to all requests and related resources
- Doing `data.resourceName.data` kind of sucks when processing a `<Query />` result

**Comment by DiederikvandenB** [comment]
Do you have an update on this issue?

**Comment by rsullivan00** [comment]
Hey @DiederikvandenB,

I think Proposal 2 above is the best path forward, but I haven't been expanding this library recently.

I'd welcome a PR if you're interested!

**Comment by DiederikvandenB** [comment]
I will have a look on of these days. Thank you for your response.

**Comment by rsullivan00** [comment]
@DiederikvandenB, I ended up taking a slightly different approach to add non-breaking support for pagination (and links and more). Check out https://github.com/Rsullivan00/apollo-link-json-api/pull/25 and let me know if it satisfies your use case.
