### ISSUE TITLE
Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by sgentry** [Rsullivan00/apollo-link-json-api#22]
I'm trying to give this library a test spin and an error is thrown that it can't "read property attributes of undefined." I see the data is fetched successfully. It looks like the method "flattenResource" is called twice. The first time it has data but on the second it is undefined. Maybe it's something with my setup. Is there a working example available that I could reference?

I've created a [codesandbox](https://codesandbox.io/s/apollo-link-json-api-v3xts) to demonstrate my issue.

**Comment by rsullivan00** [comment]
Hi @sgentry, glad you're giving it a try.

It looks like that test API is returning Resource Identifier Objects for relationships--the API I have used this library for so far only returns those when a compound document is requested with the `?include=relationship` param.

```js
// GET /authors

{
  "data":[
    {
      "type":"authors",
      "id":"2",
      "attributes":{
        "name":"testststst",
        "birthplace":"Malaysia",
        "date_of_birth":"1996-01-29",
        "date_of_death":"1983-06-19"
      },
      "relationships":{
        "photos":{
          "data":[]
        },
        "books":{
          "data":[
            { // This part is a Resource Identifier Object for the related resource.
              "type":"books",
              "id":"3"
            },
            {
              "type":"books",
              "id":"30"
            }
          ]
        }
      },
      "links":{
        "self":"\/authors\/2"
      }
    },
    ...
  ]
}
```

The Resource Identifier Objects relationship case is definitely something this library should support.

For a workaround, you could include those related resources by changing the request path from

```
authors @jsonapi(path: "/authors") {
```

to 

```
authors @jsonapi(path: "/authors?include=books,photos") {
```

Or I would welcome a PR to fix this case!

**Comment by sgentry** [comment]
Ah, thanks for looking into this! I'm still learning this spec. I'll consider making time for a PR.

**Comment by rsullivan00** [comment]
Hey @sgentry,

I ended up having some time tonight to fix that issue.

I also threw together a GraphiQL demo on top of that JSON API [here](https://optimistic-wozniak-806209.netlify.com/).

**Comment by sgentry** [comment]
Awesome, nice work and thanks for knocking this one out! I'll give it try on our internal API's when I'm back from vacation.
