### ISSUE TITLE
`Headers` is not defined when running in SSR

### ISSUE THREAD

**Issue by VinSpee** [Rsullivan00/apollo-link-json-api#27]
Hi! Very cool library. I'm trying to get it working with a Next.js App which does querying both client and server side. I'm running into this issue:

> ReferenceError: Headers is not defined
> at normalizeHeaders (project/node_modules/src/jsonApiLink.ts:593:26)
 
which leads me to [this snippet](https://github.com/Rsullivan00/apollo-link-json-api/blob/master/src/jsonApiLink.ts#L589-L598):

```ts
/**
 * Helper that makes sure our headers are of the right type to pass to Fetch
 */
export const normalizeHeaders = (
  headers: JsonApiLink.InitializationHeaders,
): Headers => {
  // Make sure that our headers object is of the right type
  if (headers instanceof Headers) {
    return headers;
  } else {
    return new Headers(headers || {});
  }
};
```

The problem is this: to create an instance of `Headers` on the server, one must use `Headers` from `node-fetch` like so:

```ts
import { Headers } from 'node-fetch';

const customHeaders = new Headers({
  'User-Agent': 'My App',
  Authorization: `Bearer ${MY_TOKEN}`,
});
```

relying on the implicit `Headers` global causes this to fail. would you be open to making `headers` more permissive?

**Comment by ins429** [comment]
I think you can polyfill `Headers` from your app side.
I know a lot of stuff in this library were copied from [apollo-link-rest](https://github.com/apollographql/apollo-link-rest) and apollo-link-rest also had [the same issue](https://github.com/apollographql/apollo-link-rest/issues/222) which suggests to polyfill the missing `Headers` from the app side.

**Comment by VinSpee** [comment]
thanks. FWIW, here's what worked for my next.js app:

```js
import clientFetch from 'unfetch';
import serverFetch, { Headers as ServerHeaders } from 'node-fetch';

const client = typeof document !== 'undefined';
global.Headers = client ? global.Headers : ServerHeaders;
const customFetch = client ? clientFetch : serverFetch;

const acmeLink = new JsonApiLink({
  …
  credentials: 'same-origin',
  customFetch,
});

```
